/* 
	https://projecteuler.net/problem=2

	Even Fibonacci numbers
	Problem 2

	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	
	*/

function sumOfEvenFibonacciNumbersLessOrEqualThanMax(maxValue) {
	let result = 2;
	let fiboNumberPrev = 1; // 1st fibo number
	let fiboNumber = 2; // 2nd fibo number
	let exceeded = false;
	let order = 0; // Every 3rd fibo numbers is even (2., 5., 8., etc)
	do {
		const newFiboNumber = fiboNumber + fiboNumberPrev;
		fiboNumberPrev = fiboNumber;
		fiboNumber = newFiboNumber;
		order++;
		if (fiboNumber <= maxValue) {
			if (order === 3) {
				result = result + fiboNumber;
				order = 0;
			}
		} else {
			exceeded = true;
		}
	} while (!exceeded);
	return result;
}

console.log("Result:", sumOfEvenFibonacciNumbersLessOrEqualThanMax(4000000));